#'''Parameters config.'''#

ext: ''
conda_prefix: ''

# --- binning_algorithms --- #

min_contig_len:   500


# --- metabat2_binning --- #

min_metabat_len:  1500


# --- concoct_binning --- #

fragment_size:    1500
overlap_size:     0


# --- vamb_binning --- #

min_bin_size: 100
test_flags: '-e 2 -t 2 -q 1'


# --- semibin_binning --- #

model_environment: 'human_gut'


# --- metabinner_binning --- #

metabinner_env: ''
checkm1_db: ''


# --- das_tool_refinement --- #

dastool_threshold: 0.5 
