#'''Parameters config.'''#

ext: ''
conda_prefix: ''

# --- binning_algorithms --- #

min_contig_len:   2500


# --- metabat2_binning --- #

min_metabat_len:  2500


# --- concoct_binning --- #

fragment_size:    2500
overlap_size:     1000


# --- vamb_binning --- #

min_bin_size:     100000
test_flags:       ''


# --- semibin_binning --- #

model_environment: 'human_gut'


# --- metabinner_binning --- #

metabinner_env: ''
checkm1_db:     ''


# --- das_tool_refinement --- #

dastool_threshold: 0.5 
