#'''Command-line usage resource config.'''#


# --- call_orfs --- #

bakta_threads: 20
bakta_mem_mb: 80000


# --- cluster_orfs --- #

mmseqs_threads: 20
mmseqs_mem_mb: 80000


# --- run_alignments --- #

diamond_threads: 20
diamond_mem_mb: 80000

